
### User sing up endpoint
POST http://localhost:3001/registerStudent
Content-Type: application/json

{
    
}
### User sing in endpoint
POST http://localhost:4000/getStudent
Content-Type: application/json 

{
    "St_Email": "Omar_Amir@gmail.com",
     "password": "password"   
}

### Get a user profile endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImUyQGUuY29tIiwiaWF0IjoxNjA5MDQ5NzE0LCJleHAiOjE2MDkxMzYxMTR9.F8cp1zteSP9OZq8NXeirub8C-Gg81UQMYGJK-OSDAlA